### ISSUE TITLE
Certificate Error when opening the website

### ISSUE THREAD

**Issue by hermionewy** [datavized/twotone#10]
**Describe the bug**
I cannot open the site (https://app.twotone.io/) and it gives me the error "ERR_CERT_COMMON_NAME_INVALID"

My Steps:
1. I used Chrome and Safari to open this URL (https://app.twotone.io/)
2. It gives me this error "ERR_CERT_COMMON_NAME_INVALID"
3. I tried to click on the "Not Secure" button before the URL and the configuration shows the certificate of "firebaseapp.com"
4. I checked multiple posts and couldn't figure out the problem

**Expected behavior**
To open that page without insecure error.

**Screenshots**

<img width="1280" alt="Screen Shot 2021-05-26 at 11 48 26 AM" src="https://user-images.githubusercontent.com/22243901/119691477-9d26f280-be18-11eb-9895-8efc9526af1e.png">

**Desktop (please complete the following information):**
 - MacOS Catalina
 - Chrome 90.0, Safari

Thanks! This is amazing work!

**Comment by pickaxemellie** [comment]
I would like to add on that I am also getting this error message with every browser/ device I use. I've highly enjoyed my time using Twotone.io and it would be a shame to no longer have access to it.
