### ISSUE TITLE
Web app down

### ISSUE THREAD

**Issue by JoseLuisRaMen** [datavized/twotone#12]
Hi there,
Not sure if you're aware, but the web app has been down for a while.
Has it been taken down on purpose?
If not, is this something you can fix?

**Comment by debraeanderson** [comment]
Hi @JoseLuisRaMen - thanks for getting in touch. We're in the process of new development on the web app and the link on twotone.io is no longer active, so for now please use this link: https://datavized.github.io/twotone/.
