### ISSUE TITLE
Missing datavized/soundq-wip dependency

### ISSUE THREAD

**Issue by kimerein** [datavized/twotone#2]
**Describe the bug**
I tried running `npm install` and got an error that seems to point to a missing repo: datavized/soundq-wip

Is it safe to comment this out of the build?

Is this available somewhere else?

Thank you in advance

**Comment by einbauch** [comment]
I have the same issue. Any updates on it?
Thank you.

**Comment by brianchirls** [comment]
Apologies for that. SoundQ is an experimental audio engine. It's public now, though not well documented here:
https://github.com/datavized/soundq

I will try to give SoundQ more love and attention over the next few months.

Please try installing again. It should work now. If you're still having a problem, we can re-open this issue.
