### ISSUE TITLE
Midi export

### ISSUE THREAD

**Issue by willpuckett** [datavized/twotone#5]
For musicians, being able to sonify a large set of data, then use attractive portions as a taking off point to loop, mix, and expand upon would be ideal. Midi export would provide a great exchange format for those who wish to go further with their sonifications.

**Comment by DystopianDisco** [comment]
+1 on MIDI export. This would make it a highly sought after tool with music producers. Is this possible to add in?

**Comment by aendra-rininsland** [comment]
This would be such a useful tool with MIDI export, it would mean producers would be able to change the samples used and not be constrained to the limited selection of instruments in the app. 

I'll happily write a PR if you'd accept it?

**Comment by cristianvogel** [comment]
we're working on a MIDI export option ... 👀
