### ISSUE TITLE
Issues with Installing Twotone

### ISSUE THREAD

**Issue by ellwoodcolahan** [datavized/twotone#6]
When I try to install twotone, this is the terminal output I get when running NPM install:

woody@woody-Virtual-Lubuntu:~$ cd twotone
woody@woody-Virtual-Lubuntu:~/twotone$ git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/master
woody@woody-Virtual-Lubuntu:~/twotone$ npm install
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
loadDep:file-selector → r ▌ ╢█████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:tslib → network   ▀ ╢███████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:promised-io → res ▄ ╢███████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDevDep:datavized-code ▄ ╢████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated eslint-loader@3.0.4: This loader has been deprecated. Please use eslint-webpack-plugin
npm ERR! git rev-list -n1 master: fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 master: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 master: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 master:
npm ERR! git rev-list -n1 master: fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 master: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 master: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 master:
loadDevDep:datavized-code ▀ ╢████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! git rev-list -n1 master: fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 master: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 master: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 master:
npm ERR! Linux 4.15.0-136-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code 128

npm ERR! Command failed: git rev-list -n1 master
npm ERR! fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/woody/twotone/npm-debug.log
woody@woody-Virtual-Lubuntu:~/twotone$ cd ..
woody@woody-Virtual-Lubuntu:~$ rm -rf twotone
woody@woody-Virtual-Lubuntu:~$ npm install --save https://github.com/datavized/twotone.git
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
loadDep:file-selector → g ▀ ╢█████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:tslib → 304       ▄ ╢██████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:promised-io → res ▌ ╢███████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

> leveldown@5.6.0 install /home/woody/node_modules/leveldown
> node-gyp-build

> core-js@2.6.12 postinstall /home/woody/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> jss@9.8.7 postinstall /home/woody/node_modules/jss
> node -e "console.log('\u001b[35m\u001b[1mLove JSS? You can now support us on open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/jss/donate\u001b[0m')"

Love JSS? You can now support us on open collective:
 > https://opencollective.com/jss/donate
npm WARN saveError ENOENT: no such file or directory, open '/home/woody/package.json'
/home/woody
└─┬ twotone@0.0.2  (git+https://github.com/datavized/twotone.git#5bab1829048610a1754aa65818ee545c6504e86f)
  ├─┬ @hot-loader/react-dom@16.14.0
  │ ├─┬ loose-envify@1.4.0
  │ │ └── js-tokens@4.0.0
  │ └── scheduler@0.19.1
  ├─┬ @material-ui/core@3.9.4
  │ ├─┬ @babel/runtime@7.13.9
  │ │ └── regenerator-runtime@0.13.7
  │ ├── @material-ui/system@3.0.0-alpha.2
  │ ├── @material-ui/utils@3.0.0-alpha.3
  │ ├─┬ @types/jss@9.5.8
  │ │ └── indefinite-observable@1.0.2
  │ ├─┬ @types/react-transition-group@2.9.2
  │ │ └─┬ @types/react@17.0.2
  │ │   ├── @types/prop-types@15.7.3
  │ │   └── csstype@3.0.7
  │ ├── brcast@3.0.2
  │ ├── csstype@2.6.16
  │ ├── deepmerge@3.3.0
  │ ├── dom-helpers@3.4.0
  │ ├── hoist-non-react-statics@3.3.2
  │ ├─┬ is-plain-object@2.0.4
  │ │ └── isobject@3.0.1
  │ ├─┬ jss@9.8.7
  │ │ ├── is-in-browser@1.1.3
  │ │ ├── symbol-observable@1.2.0
  │ │ └── warning@3.0.0
  │ ├─┬ jss-camel-case@6.1.0
  │ │ └── hyphenate-style-name@1.0.4
  │ ├── jss-default-unit@8.0.2
  │ ├── jss-global@3.0.0
  │ ├─┬ jss-nested@6.0.1
  │ │ └── warning@3.0.0
  │ ├── jss-props-sort@6.0.0
  │ ├─┬ jss-vendor-prefixer@7.0.0
  │ │ └── css-vendor@0.3.8
  │ ├── normalize-scroll-left@0.1.2
  │ ├── popper.js@1.16.1
  │ ├── react-event-listener@0.6.6
  │ ├── react-transition-group@2.9.0
  │ ├─┬ recompose@0.30.0
  │ │ ├── change-emitter@0.1.6
  │ │ ├─┬ fbjs@0.8.17
  │ │ │ ├── core-js@1.2.7
  │ │ │ ├─┬ isomorphic-fetch@2.2.1
  │ │ │ │ ├─┬ node-fetch@1.7.3
  │ │ │ │ │ ├─┬ encoding@0.1.13
  │ │ │ │ │ │ └─┬ iconv-lite@0.6.2
  │ │ │ │ │ │   └── safer-buffer@2.1.2
  │ │ │ │ │ └── is-stream@1.1.0
  │ │ │ │ └── whatwg-fetch@3.6.2
  │ │ │ ├─┬ promise@7.3.1
  │ │ │ │ └── asap@2.0.6
  │ │ │ ├── setimmediate@1.0.5
  │ │ │ └── ua-parser-js@0.7.24
  │ │ └── hoist-non-react-statics@2.5.5
  │ └── warning@4.0.3
  ├── @material-ui/icons@3.0.2
  ├─┬ @material-ui/lab@3.0.0-alpha.30
  │ └── keycode@2.2.0
  ├── audio-metadata@0.3.0
  ├── audio-recorder-polyfill@0.1.6
  ├── browser-id3-writer@4.4.0
  ├── classnames@2.2.6
  ├── debounce@1.2.0
  ├─┬ error-stack-parser@2.0.6
  │ └── stackframe@1.2.0
  ├─┬ event-emitter@0.3.5
  │ ├─┬ d@1.0.1
  │ │ └── type@1.2.0
  │ └─┬ es5-ext@0.10.53
  │   ├── es6-iterator@2.0.3
  │   ├─┬ es6-symbol@3.1.3
  │   │ └─┬ ext@1.4.0
  │   │   └── type@2.3.0
  │   └── next-tick@1.0.0
  ├── fast-deep-equal@2.0.1
  ├── file-saver@2.0.5
  ├── idb-keyval@3.2.0
  ├── ismobilejs@1.1.1
  ├─┬ jsmediatags@3.9.5
  │ └── xhr2@0.1.4
  ├─┬ lamejs@1.2.0
  │ └── use-strict@1.0.1
  ├─┬ mui-virtualized-table@2.2.3
  │ └── react-draggable@3.3.2
  ├── object-assign@4.1.1
  ├── parsecurrency@1.0.0
  ├─┬ pouchdb@7.2.2
  │ ├─┬ abort-controller@3.0.0
  │ │ └── event-target-shim@5.0.1
  │ ├── argsarray@0.0.1
  │ ├── buffer-from@1.1.1
  │ ├── clone-buffer@1.0.0
  │ ├── double-ended-queue@2.1.0-0
  │ ├─┬ fetch-cookie@0.10.1
  │ │ └─┬ tough-cookie@4.0.0
  │ │   ├── psl@1.8.0
  │ │   ├── punycode@2.1.1
  │ │   └── universalify@0.1.2
  │ ├── immediate@3.3.0
  │ ├── inherits@2.0.4
  │ ├─┬ level@6.0.1
  │ │ ├── level-js@5.0.2
  │ │ └─┬ level-packager@5.1.1
  │ │   └── encoding-down@6.3.0
  │ ├─┬ level-codec@9.0.2
  │ │ └─┬ buffer@5.7.1
  │ │   ├── base64-js@1.5.1
  │ │   └── ieee754@1.2.1
  │ ├─┬ level-write-stream@1.0.0
  │ │ └─┬ end-stream@0.1.0
  │ │   └─┬ write-stream@0.4.3
  │ │     └── readable-stream@0.0.4
  │ ├─┬ leveldown@5.6.0
  │ │ ├─┬ abstract-leveldown@6.2.3
  │ │ │ └── level-concat-iterator@2.0.1
  │ │ ├── napi-macros@2.0.0
  │ │ └── node-gyp-build@4.1.1
  │ ├─┬ levelup@4.4.0
  │ │ ├── deferred-leveldown@5.3.0
  │ │ ├─┬ level-errors@2.0.1
  │ │ │ └─┬ errno@0.1.8
  │ │ │   └── prr@1.0.1
  │ │ ├─┬ level-iterator-stream@4.0.2
  │ │ │ └── readable-stream@3.6.0
  │ │ ├── level-supports@1.0.1
  │ │ └── xtend@4.0.2
  │ ├── ltgt@2.2.1
  │ ├── node-fetch@2.6.0
  │ ├─┬ readable-stream@1.1.14
  │ │ ├── core-util-is@1.0.2
  │ │ ├── isarray@0.0.1
  │ │ └── string_decoder@0.10.31
  │ ├── spark-md5@3.0.1
  │ ├─┬ through2@3.0.2
  │ │ └─┬ readable-stream@3.6.0
  │ │   ├─┬ string_decoder@1.3.0
  │ │   │ └── safe-buffer@5.2.1
  │ │   └── util-deprecate@1.0.2
  │ ├── uuid@8.1.0
  │ └── vuvuzela@1.0.3
  ├─┬ prop-types@15.7.2
  │ └── react-is@16.13.1
  ├─┬ rc-slider@8.7.1
  │ ├─┬ babel-runtime@6.26.0
  │ │ ├── core-js@2.6.12
  │ │ └── regenerator-runtime@0.11.1
  │ ├─┬ rc-tooltip@3.7.3
  │ │ └─┬ rc-trigger@2.6.5
  │ │   ├─┬ rc-align@2.4.5
  │ │   │ └── dom-align@1.12.0
  │ │   └─┬ rc-animate@2.11.1
  │ │     ├─┬ css-animation@1.6.1
  │ │     │ └─┬ component-classes@1.2.6
  │ │     │   └── component-indexof@0.0.3
  │ │     └─┬ raf@3.4.1
  │ │       └── performance-now@2.1.0
  │ ├─┬ rc-util@4.21.1
  │ │ └── add-dom-event-listener@1.1.0
  │ ├── react-lifecycles-compat@3.0.4
  │ └── shallowequal@1.1.0
  ├── react@16.14.0
  ├── react-confirm@0.1.20
  ├── react-dom@16.14.0
  ├─┬ react-dropzone@10.2.2
  │ ├── attr-accept@2.2.2
  │ └─┬ file-selector@0.1.19
  │   └── tslib@2.1.0
  ├─┬ react-joyride@2.3.0
  │ ├── deep-diff@1.0.2
  │ ├── deepmerge@4.2.2
  │ ├── exenv@1.2.2
  │ ├── is-lite@0.8.0
  │ ├── nested-property@4.0.0
  │ ├─┬ react-floater@0.7.2
  │ │ ├── deepmerge@4.2.2
  │ │ ├── is-lite@0.6.0
  │ │ ├── react-proptype-conditional-require@1.0.4
  │ │ └─┬ tree-changes@0.5.1
  │ │   └── nested-property@1.0.1
  │ ├── scroll@3.0.1
  │ ├── scrollparent@2.0.1
  │ └─┬ tree-changes@0.6.1
  │   └── fast-deep-equal@3.1.3
  ├── react-mic-record@1.0.7  (git://github.com/datavized/react-mic-record.git#637bba3fdf179688ddf1df7a9ae1e15b63b6f321)
  ├─┬ react-sortable-hoc@1.11.0
  │ └── invariant@2.2.4
  ├─┬ react-virtualized@9.22.3
  │ ├── clsx@1.1.1
  │ └─┬ dom-helpers@5.2.0
  │   └── csstype@3.0.7
  ├─┬ serialize-error@4.1.0
  │ └── type-fest@0.3.1
  ├── soundq@0.3.0  (git://github.com/datavized/soundq.git#0d88f1ae1068440ad084351cca218a74d77992ab)
  ├─┬ standardized-audio-context@21.2.4
  │ ├─┬ automation-events@1.0.14
  │ │ └── tslib@1.14.1
  │ ├─┬ grunt-modernizr@2.1.1
  │ │ ├─┬ customizr@1.4.1
  │ │ │ ├── colors@1.4.0
  │ │ │ ├─┬ cross-spawn@7.0.3
  │ │ │ │ ├── path-key@3.1.1
  │ │ │ │ ├─┬ shebang-command@2.0.0
  │ │ │ │ │ └── shebang-regex@3.0.0
  │ │ │ │ └─┬ which@2.0.2
  │ │ │ │   └── isexe@2.0.0
  │ │ │ ├── fast-deep-equal@3.1.3
  │ │ │ ├─┬ glob@7.1.6
  │ │ │ │ ├── fs.realpath@1.0.0
  │ │ │ │ ├─┬ inflight@1.0.6
  │ │ │ │ │ └── wrappy@1.0.2
  │ │ │ │ ├─┬ minimatch@3.0.4
  │ │ │ │ │ └─┬ brace-expansion@1.1.11
  │ │ │ │ │   ├── balanced-match@1.0.0
  │ │ │ │ │   └── concat-map@0.0.1
  │ │ │ │ ├── once@1.4.0
  │ │ │ │ └── path-is-absolute@1.0.1
  │ │ │ ├── lodash@4.17.21
  │ │ │ ├── mkdirp@1.0.4
  │ │ │ ├─┬ modernizr@3.11.4
  │ │ │ │ ├─┬ doctrine@3.0.0
  │ │ │ │ │ └── esutils@2.0.3
  │ │ │ │ ├── file@0.2.2
  │ │ │ │ ├─┬ markdown-it@10.0.0
  │ │ │ │ │ ├─┬ argparse@1.0.10
  │ │ │ │ │ │ └── sprintf-js@1.0.3
  │ │ │ │ │ ├── entities@2.0.3
  │ │ │ │ │ ├── linkify-it@2.2.0
  │ │ │ │ │ ├── mdurl@1.0.1
  │ │ │ │ │ └── uc.micro@1.0.6
  │ │ │ │ ├── mkdirp@0.5.5
  │ │ │ │ ├── requirejs@2.3.6
  │ │ │ │ └─┬ yargs@15.4.1
  │ │ │ │   ├─┬ cliui@6.0.0
  │ │ │ │   │ ├─┬ strip-ansi@6.0.0
  │ │ │ │   │ │ └── ansi-regex@5.0.0
  │ │ │ │   │ └─┬ wrap-ansi@6.2.0
  │ │ │ │   │   └─┬ ansi-styles@4.3.0
  │ │ │ │   │     └─┬ color-convert@2.0.1
  │ │ │ │   │       └── color-name@1.1.4
  │ │ │ │   ├── decamelize@1.2.0
  │ │ │ │   ├─┬ find-up@4.1.0
  │ │ │ │   │ ├─┬ locate-path@5.0.0
  │ │ │ │   │ │ └─┬ p-locate@4.1.0
  │ │ │ │   │ │   └─┬ p-limit@2.3.0
  │ │ │ │   │ │     └── p-try@2.2.0
  │ │ │ │   │ └── path-exists@4.0.0
  │ │ │ │   ├── get-caller-file@2.0.5
  │ │ │ │   ├── require-directory@2.1.1
  │ │ │ │   ├── require-main-filename@2.0.0
  │ │ │ │   ├── set-blocking@2.0.0
  │ │ │ │   ├─┬ string-width@4.2.2
  │ │ │ │   │ ├── emoji-regex@8.0.0
  │ │ │ │   │ └── is-fullwidth-code-point@3.0.0
  │ │ │ │   ├── which-module@2.0.0
  │ │ │ │   ├── y18n@4.0.1
  │ │ │ │   └─┬ yargs-parser@18.1.3
  │ │ │ │     └── camelcase@5.3.1
  │ │ │ ├─┬ nopt@4.0.3
  │ │ │ │ ├── abbrev@1.1.1
  │ │ │ │ └─┬ osenv@0.1.5
  │ │ │ │   ├── os-homedir@1.0.2
  │ │ │ │   └── os-tmpdir@1.0.2
  │ │ │ ├─┬ optimist@0.6.1
  │ │ │ │ ├── minimist@0.0.10
  │ │ │ │ └── wordwrap@0.0.3
  │ │ │ └── promised-io@0.3.6
  │ │ └── lodash.merge@4.6.2
  │ └── tslib@1.14.1
  ├── to-id@2.0.0
  ├── unistore@3.5.2
  ├── wav-encoder@1.3.0
  ├── UNMET PEER DEPENDENCY webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0
  ├─┬ worker-loader@2.0.0
  │ ├─┬ loader-utils@1.4.0
  │ │ ├── big.js@5.2.2
  │ │ ├── emojis-list@3.0.0
  │ │ └─┬ json5@1.0.1
  │ │   └── minimist@1.2.5
  │ └─┬ schema-utils@0.4.7
  │   ├─┬ ajv@6.12.6
  │   │ ├── fast-deep-equal@3.1.3
  │   │ ├── fast-json-stable-stringify@2.1.0
  │   │ ├── json-schema-traverse@0.4.1
  │   │ └── uri-js@4.4.1
  │   └── ajv-keywords@3.5.2
  └─┬ xlsx@0.15.6
    ├─┬ adler-32@1.2.0
    │ └── printj@1.1.2
    ├── cfb@1.2.0
    ├─┬ codepage@1.14.0
    │ └── commander@2.14.1
    ├── commander@2.17.1
    ├── crc-32@1.2.0
    ├── exit-on-epipe@1.0.1
    ├─┬ ssf@0.10.3
    │ └── frac@1.1.2
    └── wmf@1.0.2

npm WARN enoent ENOENT: no such file or directory, open '/home/woody/package.json'
npm WARN worker-loader@2.0.0 requires a peer of webpack@^3.0.0 || ^4.0.0-alpha.0 || ^4.0.0 but none was installed.
npm WARN woody No description
npm WARN woody No repository field.
npm WARN woody No README data
npm WARN woody No license field.
woody@woody-Virtual-Lubuntu:~$ ^C
woody@woody-Virtual-Lubuntu:~$

**Comment by kimpham54** [comment]
on a mac I get the following error:
```
npm install

> fsevents@1.2.13 install /Users/kimpham/Desktop/twotone/node_modules/fork-ts-checker-webpack-plugin/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> nodent-runtime@3.2.1 install /Users/kimpham/Desktop/twotone/node_modules/nodent-runtime
> node build.js

## Built /Users/kimpham/Desktop/twotone/node_modules/nodent-runtime/dist/index.js

> fsevents@1.2.13 install /Users/kimpham/Desktop/twotone/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> fsevents@1.2.13 install /Users/kimpham/Desktop/twotone/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node

> sharp@0.25.4 install /Users/kimpham/Desktop/twotone/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-darwin-x64.tar.gz

> leveldown@5.6.0 install /Users/kimpham/Desktop/twotone/node_modules/leveldown
> node-gyp-build


> core-js@2.6.12 postinstall /Users/kimpham/Desktop/twotone/node_modules/@babel/polyfill/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/bmp/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/core/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/custom/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/gif/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/jpeg/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-blit/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-blur/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-circle/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-color/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-contain/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-cover/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-crop/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-displace/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-dither/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-fisheye/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-flip/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-gaussian/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-invert/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-mask/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-normalize/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-print/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-resize/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-rotate/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-scale/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-shadow/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugin-threshold/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/plugins/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/png/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/tiff/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/types/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/@jimp/utils/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@2.6.12 postinstall /Users/kimpham/Desktop/twotone/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js-pure@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@2.7.4 postinstall /Users/kimpham/Desktop/twotone/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> core-js@3.8.3 postinstall /Users/kimpham/Desktop/twotone/node_modules/jimp/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> jss@9.8.7 postinstall /Users/kimpham/Desktop/twotone/node_modules/jss
> node -e "console.log('\u001b[35m\u001b[1mLove JSS? You can now support us on open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/jss/donate\u001b[0m')"

Love JSS? You can now support us on open collective:
 > https://opencollective.com/jss/donate

> core-js@2.6.12 postinstall /Users/kimpham/Desktop/twotone/node_modules/unused-files-webpack-plugin/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> gifsicle@4.0.1 postinstall /Users/kimpham/Desktop/twotone/node_modules/gifsicle
> node lib/install.js

  ✔ gifsicle pre-build test passed successfully

> jpegtran-bin@4.0.0 postinstall /Users/kimpham/Desktop/twotone/node_modules/jpegtran-bin
> node lib/install.js

  ✔ jpegtran pre-build test passed successfully

> mozjpeg@6.0.1 postinstall /Users/kimpham/Desktop/twotone/node_modules/mozjpeg
> node lib/install.js

  ✔ mozjpeg pre-build test passed successfully

> optipng-bin@5.1.0 postinstall /Users/kimpham/Desktop/twotone/node_modules/optipng-bin
> node lib/install.js

  ✔ optipng pre-build test passed successfully

> pngquant-bin@5.0.2 postinstall /Users/kimpham/Desktop/twotone/node_modules/pngquant-bin
> node lib/install.js

  ✔ pngquant pre-build test passed successfully
npm WARN twotone@0.0.2 No repository field.

added 2072 packages from 1168 contributors and audited 2078 packages in 92.327s

83 packages are looking for funding
  run `npm fund` for details

found 7 vulnerabilities (5 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
(base) LIB-C02WT136HV2T:twotone kimpham$ npm run start

> twotone@0.0.2 start /Users/kimpham/Desktop/twotone
> NODE_ENV=development webpack-dev-server

internal/modules/cjs/loader.js:548
  throw e;
  ^

Error: Package exports for '/Users/kimpham/Desktop/twotone/node_modules/colorette' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:545:13)
    at applyExports (internal/modules/cjs/loader.js:459:14)
    at resolveExports (internal/modules/cjs/loader.js:508:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:577:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:879:27)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/kimpham/Desktop/twotone/node_modules/autoprefixer/lib/autoprefixer.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/kimpham/Desktop/twotone/webpack.config.js:31:22) {
  code: 'MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twotone@0.0.2 start: `NODE_ENV=development webpack-dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the twotone@0.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
