### ISSUE TITLE
Cannot start on Windows

### ISSUE THREAD

**Issue by davidmoten** [datavized/twotone#9]
On Windows I succeed with `npm install` but on `npm run start` I get:

```
'NODE_ENV' is not recognized as an internal or external command
```

I assume that an environment variable needs to be set in a subtly different way on Windows (`set NODE_ENV=blah` instead of `NODE_ENV=blah`). Can you look at this please?

I'm using the latest commit on master (5bab1829048610a1754aa65818ee545c6504e86f).

**Comment by davidmoten** [comment]
For anyone else encountering this I went with a workaround of installing the Ubuntu 20.04 app on Windows 10 and then `sudo apt install npm git` after which the normal build instructions work fine. Would still be nice if someone solved the issue though.

**Comment by enadol** [comment]
Same here on Windows 10. Here's the complete log output.

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle twotone@0.0.2~prestart: twotone@0.0.2
6 info lifecycle twotone@0.0.2~start: twotone@0.0.2
7 verbose lifecycle twotone@0.0.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle twotone@0.0.2~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\enado\twotone\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\PuTTY\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Ruby30-x64\bin;C:\Users\enado\AppData\Local\Programs\Python\Python38-32\Scripts\;C:\Users\enado\AppData\Local\Programs\Python\Python38-32\;C:\Users\enado\AppData\Local\Microsoft\WindowsApps;C:\Users\enado\AppData\Roaming\npm
9 verbose lifecycle twotone@0.0.2~start: CWD: C:\Users\enado\twotone
10 silly lifecycle twotone@0.0.2~start: Args: [ '/d /s /c', 'NODE_ENV=development webpack-dev-server' ]
11 silly lifecycle twotone@0.0.2~start: Returned: code: 1  signal: null
12 info lifecycle twotone@0.0.2~start: Failed to exec start script
13 verbose stack Error: twotone@0.0.2 start: `NODE_ENV=development webpack-dev-server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid twotone@0.0.2
15 verbose cwd C:\Users\enado\twotone
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v14.16.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error twotone@0.0.2 start: `NODE_ENV=development webpack-dev-server`
22 error Exit status 1
23 error Failed at the twotone@0.0.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by davidmoten** [comment]
this was closed because it's fixed?

**Comment by cristianvogel** [comment]
Sorry, no we are pruning and migrating for further developments.
